apiVersion: apps/v1
kind: Deployment
metadata:
  name: projectcapstoneindex
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: projectcapstoneindex
  template:
    metadata:
      labels:
        app: projectcapstoneindex
    spec:
      containers:
        - name: projectcapstoneindex
          image: vikrantarora14/projectcapstoneindex
          imagePullPolicy: Always
          ports:
            - containerPort: 9000